/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 A220_4.gltf --transform 
Files: A220_4.gltf [8.68MB] > A220_4-transformed.glb [644.89KB] (93%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/A220_4-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube030.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Cube030_1.geometry} material={materials['Interior A220']} />
      <mesh geometry={nodes.Cube030_2.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.Cube030_3.geometry} material={materials.PaletteMaterial003} />
    </group>
  )
}

useGLTF.preload('/A220_4-transformed.glb')
